### ISSUE TITLE
Define valid output fields for all commands

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/blast#17]
At the moment valid output fields (`AnyBlastCommand#OutputFields` it's called in master) are defined only for `blastn`. And as it's only a type member, compiler doesn't complain that it's not defined :-1:

**Comment by eparejatobes** [comment]
There are some really generic ones that we could put there while we do some research on it

**Comment by eparejatobes** [comment]
actually, those set in `blastn` now are OK for all cmds

**Comment by eparejatobes** [comment]
done in #16
